name: Test SSH

on:
  push:
      branches: [main]
  workflow_dispatch:

env:
  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  USER_NAME: 'Nikhil Menghani'
  EMAIL: 'nikhil@menghani.com'

jobs:
  build:
    runs-on: macos-latest

    steps:
       - name: Checkout
         uses: actions/checkout@main
       
       - name: kielabokkie
         uses: kielabokkie/ssh-key-and-known-hosts-action@v1
         with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            ssh-host: gitlab.com

       - name: Environment Details and clean up
         run: |
            ls -R
            rm -rf build
            cat /Users/runner/.ssh/known_hosts
       - name: Initialization and Fetching the Source Code
         run: |
            git config --global user.name "Nikhil Menghani"
            git config --global user.email "nikhil@menghani.com"
            git clone git@gitlab.com:nikhilmenghani/test.git
            
